# Configuration files for ansible playbook (default variables for prereq role)
packages:
  debian:
    - openssh
    - python3
    - python3-pip

  darwin:
    - python3
    - wget
    - git
    - curl
  arch:
    - python3
    - python3-pip
    - wget
    - git
    - curl
  alpine:
    - python3
    - py3-pip
    - vim
    - wget
    - git
    - curl